version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
    - location: deployment_scripts/pre-install.sh
      runas: root
  AfterInstall:
    - location: deployment_scripts/post-install.sh
      timeout: 180
  ApplicationStart:
    - location: deployment_scripts/start_application.sh