export const LOAD_CRIMES_SUCCESS = 'LOAD_CRIMES_SUCCESS';
export const LOAD_CRIMES_INITIAL_SUCCESS = 'LOAD_CRIMES_INITIAL_SUCCESS';
export const LOAD_CRIME_CATEGORIES_SUCCESS = 'LOAD_CRIME_CATEGORIES_SUCCESS';
export const LOAD_CRIME_DATES_SUCCESS = 'LOAD_CRIME_DATES_SUCCESS';
