export const LOAD_CRIMES_SUCCESS = 'LOAD_CRIMES_SUCCESS';
export const LOAD_CRIMES_INITIAL_SUCCESS = 'LOAD_CRIMES_INITIAL_SUCCESS';
export const LOAD_CRIME_CATEGORIES_SUCCESS = 'LOAD_CRIME_CATEGORIES_SUCCESS';
export const LOAD_CRIME_DATES_SUCCESS = 'LOAD_CRIME_DATES_SUCCESS';
export const LOAD_HOT_SPOTS_SUCCESS = 'LOAD_HOT_SPOTS_SUCCESS';
export const LOAD_HOT_SPOTS_INITIAL_SUCCESS = 'LOAD_HOT_SPOTS_INITIAL_SUCCESS';
export const LOAD_CRIME_TOTALS_SUCCESS = 'LOAD_CRIME_TOTALS_SUCCESS';
export const LOAD_CRIME_TOTALS_INITIAL_SUCCESS = 'LOAD_CRIME_TOTALS_INITIAL_SUCCESS';
